// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmE6kEIkl-yFhH1GLqw3yXqHqjCHNd10I',
    appId: '1:755907993091:web:6e1650ed8645be3c3bf836',
    messagingSenderId: '755907993091',
    projectId: 'inventory-management-93389',
    authDomain: 'inventory-management-93389.firebaseapp.com',
    storageBucket: 'inventory-management-93389.firebasestorage.app',
    measurementId: 'G-BGMH59C9BX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUYIejJx8KlT2IpJ3-t0sZD5SLEoir5us',
    appId: '1:755907993091:android:b1236706fac230593bf836',
    messagingSenderId: '755907993091',
    projectId: 'inventory-management-93389',
    storageBucket: 'inventory-management-93389.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkITKg1xQAHZqK1AnVgeFV884jo5hDn3E',
    appId: '1:755907993091:ios:85d9131d798178233bf836',
    messagingSenderId: '755907993091',
    projectId: 'inventory-management-93389',
    storageBucket: 'inventory-management-93389.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkITKg1xQAHZqK1AnVgeFV884jo5hDn3E',
    appId: '1:755907993091:ios:85d9131d798178233bf836',
    messagingSenderId: '755907993091',
    projectId: 'inventory-management-93389',
    storageBucket: 'inventory-management-93389.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmE6kEIkl-yFhH1GLqw3yXqHqjCHNd10I',
    appId: '1:755907993091:web:e671c3c5951e9d063bf836',
    messagingSenderId: '755907993091',
    projectId: 'inventory-management-93389',
    authDomain: 'inventory-management-93389.firebaseapp.com',
    storageBucket: 'inventory-management-93389.firebasestorage.app',
    measurementId: 'G-GE30V2W08F',
  );
}
